# with external configuration:
spring:
  application:
    name: schools
  config:
    import: optional:configserver:http://localhost:8888


# if our configuration will be here:
#spring:
#  application:
#    name: school
#  config:
#    import: optional:configserver:http://localhost:8888
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/schools
#    username: postgres
#    password: admin123
#  jpa:
#    hibernate:
#      ddl-auto: create
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#server:
#  port: 8070
#
## configurations for our discovery client
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#
#application:
#  config:
#    students-url: http://localhost:8090/api/v1/students