#with external config
spring:
  application:
    name: students
  config:
    import: optional:configserver:http://localhost:8888

#with internal config
#spring:
#  application:
#    name: student
#  config:
#    import: optional:configserver:http://localhost:8888
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/students
#    username: postgres
#    password: admin123
#  jpa:
#    hibernate:
#      ddl-auto: create
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#server:
#  port: 8090
#
## configurations for our discovery client
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#
